version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - nlemoine
  versioning-strategy: increase
  ignore:
  - dependency-name: gulp-filter
    versions:
    - 7.0.0
  - dependency-name: mem
    versions:
    - 8.1.1
  - dependency-name: browserslist
    versions:
    - 4.16.3
    - 4.16.5
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.9
  - dependency-name: gulp-replace
    versions:
    - 1.1.1
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: cssnano
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: rollup
    versions:
    - 2.38.2
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.42.1
    - 2.43.1
    - 2.44.0
    - 2.45.1
    - 2.45.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.15
    - 7.13.8
    - 7.13.9
  - dependency-name: memfs
    versions:
    - 3.2.1
    - 3.2.2
  - dependency-name: mime-types
    versions:
    - 2.1.30
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
    - 11.2.1
  - dependency-name: gulp-modernizr
    versions:
    - 4.0.2
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
    - 18.0.0
  - dependency-name: gulp-append-prepend
    versions:
    - 1.0.9
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - 5.2.3
    - 5.3.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
