version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "nlemoine"
    version_requirement_updates: "increase_versions"
